version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: my-next-app:latest

    env_file:
      - .env.production

    ports:
      - "3000:3000"

    restart: unless-stopped
    environment:
      PORT: "3000"
      HOSTNAME: "0.0.0.0"

    read_only: true
    tmpfs:
      - /tmp 
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://127.0.0.1:'+(process.env.PORT||3000), r=>process.exit((r.statusCode>=200&&r.statusCode<500)?0:1)).on('error',()=>process.exit(1))\""]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

    networks:
      - webnet

networks:
  webnet:
    driver: bridge
